language: android
dist: trusty
jdk:
  - openjdk8
android:
  components:
    - build-tools-29.0.2
    - android-29
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew test